### PR TITLE
fix Makefile issues (#694) by handling code not terminated by a new line

### LINKED ISSUE #694: Makefile highlighting always incorrect (even for trivial Makefiles)
I updated from a very old version, and now all the makefile highlights are completely wrong.  Is current makefile support still useful?

See, e.g.:  http://rouge.jneen.net/pastes/E96e

I would not expect reverse bright red in one rule but not in the other

(edit: changed the example to a simpler one)

### PR DESCRIPTION
**Pull request by gfx**
Fix #694, thanks to @dblessing for investigating the issue.

### CODE REVIEW

File: spec/lexers/make_spec.rb [hunk 1]
```diff
@@ -22,4 +22,13 @@
       assert_guess :source => '.PHONY: all'
     end
   end
+
+  describe 'lexing' do
+    include Support::Lexing
+
+    it 'recognizes declarations not terminated by a new line (#694)' do
+      assert_tokens_equal "hello: \n\techo hello",
+       ["Name.Label", "hello"], ["Operator", ":"], ["Text", " \n\t"], ["Name.Builtin", "echo "], ["Text", "hello"]
```
Comment (gfx) [inline spec/lexers/make_spec.rb]: It was `[["Name.Label", "hello"], ["Operator", ":"], ["Text", " \n\t"], ["Error", "echo hello"]]` as issued.

File: lib/rouge/lexers/make.rb [hunk 2]
```diff
@@ -96,7 +96,7 @@ def initialize(opts={})
         end
 
         rule(/\\./m) { delegate @shell }
-        stop = /\$\(|\(|\)|\n|\\/
+        stop = /\$\(|\(|\)|\n|\\|$/
```
Comment (jneen) [inline lib/rouge/lexers/make.rb]: can we drop the `\n` from this regex? I think it should be delegated to the shell lexer anyways.

Comment (gfx) [inline lib/rouge/lexers/make.rb]: Indeed 2c181a7
