### PR TITLE
Kotlin: fix generic functions

### LINKED ISSUE #736: Kotlin rendering issue
Generic functions are badly rendered

screen shot 2017-07-31 at 22 16 40

### PR DESCRIPTION
**Pull request by gfx**
Fix #736.

There ware two ways to handle nested syntax in Rouge:

1. Use state. https://github.com/jneen/rouge/blob/master/lib/rouge/lexers/ruby.rb is a good example
2. Use regexp to handle only keywords and punctuations

*1)* is better but difficult. In this PR, just use regexp for `fun`.

related: #770

screen shot 2017-09-19 at 10 41 38

### CODE REVIEW

File: lib/rouge/lexers/kotlin.rb [hunk 1]
```diff
@@ -56,10 +58,7 @@ class Kotlin < RegexLexer
           groups Keyword::Declaration, Text
           push :property
         end
-        rule %r'(fun)(\s+)' do
-          groups Keyword, Text
-          push :function
-        end
+        rule %r/fun/, Keyword
```
Comment (jneen) [inline lib/rouge/lexers/kotlin.rb]: Looks good! But I would add a `\b` at the end to make sure it doesn't match `funny` for example.

Comment (gfx) [reply lib/rouge/lexers/kotlin.rb]: Oh! I've misunderstood it because there are too many /keyword/ there.

Fixed in f798dd4

**Comment by lordcodes** [comment]
@gfx I believe this PR caused #792. I rolled back the rouge gem to 2.2.1 just before the PR was merged and Kotlin functions are correctly highlighted. However, now they are no longer highlighted and just show as regular 'Name' tokens.
